const data = [
  "Accounting / Finance",
  "Administrations / Office Management",
  "Agriculture / Farming",
  "Auditing",
  "Aviations",
  "Banking",
  "Business development",
  "Cleansing services",
  "Commercial / Sales",
  "Communication",
  "Construction / Architecture",
  "Consulting / Research",
  "Cosmetics",
  "Customer Services",
  "Driving",
  "Economics",
  "Education /Training",
  "Electrical engineering",
  "Electronics",
  "Engineering",
  "Environment / Energy",
  "Event management",
  "Executive / Top Management",
  "Facility management",
  "Goverment Jobs",
  "Graphic Design/video editing",
  "Healthcare / Pharmaceutical",
  "Home Care Service",
  "Hotel / Restaurant / Catering",
  "Human Resources / Recruitment",
  "Installation / Maintenance",
  "Insurance",
  "IT / Engineering",
  "Legal",
  "Marketing",
  "Mathematics",
  "Media / Journalism",
  "Micro Finance",
  "Monitoring / Evaluation",
  "NGOs / Social Work",
  "Operations",
  "Other",
  "Photography",
  "Printing",
  "Procurement / Supply chain",
  "Programs",
  "Project Management",
  "Public Relations",
  "Public Tender",
  "Real estate",
  "Repair and Maintenance",
  "Security Service",
  "Social media / Digital Marketing",
  "Social Worker",
  "Supply and Delivery",
  "Tailoring",
  "Tender Notice",
  "Tourism and Hospitality",
  "Transport / Logistics",
  "Waste Management",
  "Writing & Publishing",
];

const CompanyCategory = data.map((item, index) => ({
  id: index + 1,
  name: item,
}));

export { CompanyCategory };
