import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import UserContextProvider from "./Providers";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";

const inter = Inter({ subsets: ["cyrillic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <UserContextProvider>
          <Header />
          <main> {children}</main>
          <Footer />
          <ScrollToTop />
        </UserContextProvider>
        <Toaster />
      </body>
    </html>
  );
}
